services:
  - type: web
    name: foundation-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: foundation-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".render.com"

databases:
  - name: foundation-db
    plan: free
